export const LANG = {
  en: {
    appSub: 'Bofo Waterproofing Systems',
    formTitle: 'Request form',
    formSub: 'Submit a material, tool, or other request',
    adminTitle: 'Admin dashboard',
    adminSub: 'Manage and update all submissions',
    navForm: 'New request',
    navLog: 'Submissions',
    navAdmin: 'Admin',
    employeeName: 'Employee',
    jobSite: 'Job site',
    requestType: 'Request type',
    brand: 'Brand',
    workType: 'Type of Work',
    selectWorkType: 'Select type...',
    product: 'Product',
    tool: 'Tool',
    describeItem: 'Describe item',
    quantity: 'Quantity',
    notes: 'Notes',
    notesPlaceholder: 'Additional details or instructions...',
    submit: 'Submit request',
    submitting: 'Submitting...',
    selectName: 'Select name...',
    selectSite: 'Select site...',
    selectBrand: 'Select brand...',
    selectTool: 'Select tool...',
    selectProduct: 'Select product...',
    productPlaceholder: 'e.g. TREMproof 250GC',
    descPlaceholder: 'What do you need?',
    material: 'Material',
    toolType: 'Tool',
    other: 'Other',
    successTitle: 'Request submitted',
    successSub: 'Your request has been logged and is pending review.',
    newRequest: 'Submit another request',
    logEmpty: 'No submissions yet.',
    adminEmpty: 'No submissions yet.',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusCompleted: 'Completed',
    required: 'Please fill in all required fields.',
    errorMsg: 'Something went wrong. Please try again.',
    details: 'Details',
    qty: 'Qty',
    markApproved: 'Approve',
    markCompleted: 'Complete',
    markPending: 'Reset',
    allStatuses: 'All statuses',
    allSites: 'All sites',
    searchPlaceholder: 'Search by name or site...',
    totalSubmissions: 'Total',
    pendingCount: 'Pending',
    approvedCount: 'Approved',
    completedCount: 'Completed',
    neededBy: 'Needed by',
    neededByPlaceholder: 'e.g. ASAP, Friday, end of week...',
    priority: 'Priority',
    priorityUrgent: 'Urgent',
    priorityNormal: 'Normal',
    tools: ['Caulking Gun', 'Heat Gun', 'Mixer / Drill', 'Notched Trowel', 'Roller', 'Sprayer', 'Grinder', 'Power Washer', 'Rope', 'Hose'],
    whenNeeded: 'When needed?',
    timingOptions: [
      { label: 'ASAP',      priority: 'urgent' },
      { label: 'Today',     priority: 'urgent' },
      { label: 'Tomorrow',  priority: 'normal' },
      { label: '2–3 Days',  priority: 'normal' },
      { label: 'This Week', priority: 'normal' },
    ],
    navReport: 'Work Report',
    reportTitle: 'Daily Work Report',
    reportSub: 'Submit end-of-day progress photos',
    reportSuccessTitle: 'Report submitted',
    reportSuccessSub: 'Photos and notes saved successfully.',
    newReport: 'Submit another report',
    adminRequestsTab: 'Requests',
    adminReportsTab: 'Work Reports',
    adminLocationsTab: 'Locations',
    adminLinkText: 'Admin',
    exitAdmin: 'Exit',
    pinTitle: 'Admin access',
    pinPlaceholder: 'Enter PIN',
    pinUnlock: 'Unlock',
    pinError: 'Incorrect PIN.',
    pinBack: 'Back',
    downloadZip: 'Download ZIP',
    exportPdf: 'Export PDF',
    downloadAll: 'Download All',
    buildingZip: 'Building ZIP…',
    generatingPdf: 'Generating PDF…',
    // Admin manage tabs
    manageSitesTab: 'Sites',
    manageEmployeesTab: 'Employees',
    manageMaterialsTab: 'Materials',
    manageToolsUnitsTab: 'Tools & Units',
    // Manage section titles
    employeesSection: 'Employees',
    brandsSection: 'Brands',
    workTypesSection: 'Work Types',
    productsSection: 'Products',
    toolsSection: 'Tools',
    unitsSection: 'Units',
    // Manage actions
    add: 'Add',
    adding: 'Adding…',
    // Manage placeholders
    newEmployeePlaceholder: 'New employee name…',
    newBrandPlaceholder: 'New brand…',
    newWorkTypePlaceholder: 'New work type…',
    newProductPlaceholder: 'New product name…',
    newToolPlaceholder: 'New tool…',
    newUnitPlaceholder: 'New unit…',
    // Manage messages
    itemExists: 'Already in the list.',
    addFailed: 'Failed to add. Try again.',
    deleteFailed: 'Failed to remove. Try again.',
    noItemsYet: 'No items yet.',
    selectBrandForProducts: 'Select a brand and work type to manage products.',
    // AdminDashboard new filters
    allEmployees: 'All employees',
    allTypes: 'All types',
    typeMaterial: 'Material',
    typeTool: 'Tool',
    typeOther: 'Other',
    // DailyReportForm
    reportEmployee: 'Employee',
    reportSite: 'Job Site',
    reportPhotos: 'Photos',
    reportAddPhotos: '+ Add Photos',
    reportSubmit: 'Submit Report',
    reportSubmitting: 'Submitting…',
    reportNotesPlaceholder: 'Work completed, progress updates, issues from the field…',
    reportUploadProgress: 'Uploading photos…',
    reportUploadPartialFail: 'photo(s) could not be uploaded — report submitted with the rest.',
    reportAllFailed: 'All photos failed to upload. Check your connection and try again.',
    reportMinPhotos: 'at least',
    reportMinPhotosRequired: 'required',
  },
  es: {
    workType: 'Tipo de trabajo',
    selectWorkType: 'Selecciona tipo...',
    appSub: 'Bofo Waterproofing Systems',
    formTitle: 'Formulario de solicitud',
    formSub: 'Envía una solicitud de material, herramienta u otro',
    adminTitle: 'Panel de administración',
    adminSub: 'Gestiona y actualiza todas las solicitudes',
    navForm: 'Nueva solicitud',
    navLog: 'Envíos',
    navAdmin: 'Admin',
    employeeName: 'Empleado',
    jobSite: 'Sitio de trabajo',
    requestType: 'Tipo de solicitud',
    brand: 'Marca',
    product: 'Producto',
    tool: 'Herramienta',
    describeItem: 'Describir artículo',
    quantity: 'Cantidad',
    notes: 'Notas',
    notesPlaceholder: 'Detalles o instrucciones adicionales...',
    submit: 'Enviar solicitud',
    submitting: 'Enviando...',
    selectName: 'Selecciona nombre...',
    selectSite: 'Selecciona sitio...',
    selectBrand: 'Selecciona marca...',
    selectTool: 'Selecciona herramienta...',
    productPlaceholder: 'ej. TREMproof 250GC',
    descPlaceholder: '¿Qué necesitas?',
    material: 'Material',
    toolType: 'Herramienta',
    other: 'Otro',
    successTitle: 'Solicitud enviada',
    successSub: 'Tu solicitud ha sido registrada y está pendiente de revisión.',
    newRequest: 'Enviar otra solicitud',
    logEmpty: 'Sin envíos aún.',
    adminEmpty: 'Sin envíos aún.',
    statusPending: 'Pendiente',
    statusApproved: 'Aprobado',
    statusCompleted: 'Completado',
    required: 'Por favor completa todos los campos requeridos.',
    errorMsg: 'Algo salió mal. Por favor intenta de nuevo.',
    details: 'Detalles',
    qty: 'Cantidad',
    markApproved: 'Aprobar',
    markCompleted: 'Completar',
    markPending: 'Restablecer',
    allStatuses: 'Todos los estados',
    allSites: 'Todos los sitios',
    searchPlaceholder: 'Buscar por nombre o sitio...',
    totalSubmissions: 'Total',
    pendingCount: 'Pendientes',
    approvedCount: 'Aprobados',
    completedCount: 'Completados',
    tools: ['Pistola de sellado', 'Pistola de calor', 'Mezclador / Taladro', 'Llana dentada', 'Rodrillo', 'Rociador', 'Amoladora', 'Hidrolavadora', 'Cuerda', 'Mangera'],
    selectProduct: 'Selecciona producto...',
    neededBy: 'Necesito para',
    neededByPlaceholder: 'ej. Lo antes posible, viernes, fin de semana...',
    priority: 'Prioridad',
    priorityUrgent: 'Urgente',
    priorityNormal: 'Normal',
    whenNeeded: '¿Cuándo?',
    timingOptions: [
      { label: 'ASAP',        priority: 'urgent' },
      { label: 'Hoy',         priority: 'urgent' },
      { label: 'Mañana',      priority: 'normal' },
      { label: '2–3 Días',    priority: 'normal' },
      { label: 'Esta Semana', priority: 'normal' },
    ],
    navReport: 'Reporte de Trabajo',
    reportTitle: 'Reporte Diario de Trabajo',
    reportSub: 'Enviar fotos de progreso del día',
    reportSuccessTitle: 'Reporte enviado',
    reportSuccessSub: 'Fotos y notas guardadas exitosamente.',
    newReport: 'Enviar otro reporte',
    adminRequestsTab: 'Solicitudes',
    adminReportsTab: 'Reportes de Trabajo',
    adminLocationsTab: 'Ubicaciones',
    adminLinkText: 'Admin',
    exitAdmin: 'Salir',
    pinTitle: 'Acceso de administrador',
    pinPlaceholder: 'Ingresa el PIN',
    pinUnlock: 'Desbloquear',
    pinError: 'PIN incorrecto.',
    pinBack: 'Volver',
    downloadZip: 'Descargar ZIP',
    exportPdf: 'Exportar PDF',
    downloadAll: 'Descargar todo',
    buildingZip: 'Creando ZIP…',
    generatingPdf: 'Generando PDF…',
    // Admin manage tabs
    manageSitesTab: 'Sitios',
    manageEmployeesTab: 'Empleados',
    manageMaterialsTab: 'Materiales',
    manageToolsUnitsTab: 'Herramientas y Unidades',
    // Manage section titles
    employeesSection: 'Empleados',
    brandsSection: 'Marcas',
    workTypesSection: 'Tipos de Trabajo',
    productsSection: 'Productos',
    toolsSection: 'Herramientas',
    unitsSection: 'Unidades',
    // Manage actions
    add: 'Agregar',
    adding: 'Agregando…',
    // Manage placeholders
    newEmployeePlaceholder: 'Nuevo nombre de empleado…',
    newBrandPlaceholder: 'Nueva marca…',
    newWorkTypePlaceholder: 'Nuevo tipo de trabajo…',
    newProductPlaceholder: 'Nuevo nombre de producto…',
    newToolPlaceholder: 'Nueva herramienta…',
    newUnitPlaceholder: 'Nueva unidad…',
    // Manage messages
    itemExists: 'Ya está en la lista.',
    addFailed: 'No se pudo agregar. Intenta de nuevo.',
    deleteFailed: 'No se pudo eliminar. Intenta de nuevo.',
    noItemsYet: 'Aún no hay elementos.',
    selectBrandForProducts: 'Selecciona una marca y tipo de trabajo para gestionar productos.',
    // AdminDashboard new filters
    allEmployees: 'Todos los empleados',
    allTypes: 'Todos los tipos',
    typeMaterial: 'Material',
    typeTool: 'Herramienta',
    typeOther: 'Otro',
    // DailyReportForm
    reportEmployee: 'Empleado',
    reportSite: 'Sitio de trabajo',
    reportPhotos: 'Fotos',
    reportAddPhotos: '+ Agregar fotos',
    reportSubmit: 'Enviar reporte',
    reportSubmitting: 'Enviando…',
    reportNotesPlaceholder: 'Trabajo completado, actualizaciones de progreso, problemas del campo…',
    reportUploadProgress: 'Subiendo fotos…',
    reportUploadPartialFail: 'foto(s) no se pudieron subir — reporte enviado con el resto.',
    reportAllFailed: 'No se pudieron subir las fotos. Verifica tu conexión e intenta de nuevo.',
    reportMinPhotos: 'mínimo',
    reportMinPhotosRequired: 'requeridas',
  }
};

export const EMPLOYEES = [
  'Christian Almanza',
  'Vladimir Barranca',
  'James Brown',
  'Juan Cerda',
  'Aleks V. Cerda',
  'Everado Diaz Cisneros',
  'Salvador Gonzalez',
  'Juan D. Hernandez',
  'Carlos Leyva',
  'Francisco Lopez',
  'Miguel Marquez',
  'Jose Martinez',
  'Elias Meraz',
  'Hector Pantoja Galves',
  'Manuel Toledo',
  'Daniel Sanchez',
  'Rafael A. Sanchez',
];

export const JOB_SITES = [
  'Franciscan Hospital - Munster',
  'Ravinia Phase 2',
  '537 W. Drummond',
  'Oak Park River Forest High School',
  'Sacred Apartments',
  'Leyden Community Center',
  'CDA TP09 - MCP Building',
  "O'Hare Terminal 3",
  '2355 W. 63rd St.',
  'South Side Community Center',
  'U-Haul Frankfort',
  'Fernway School',
  'Regents Park Lobby',
  'Spaulding School',
  'Project Lighthouse',
  'North Shore Water Reclamation',
  'Legends South',
  'Rivian Oakbrook',
  'Evanston Township School',
  'Demeter 4.0',
  'Helen Keller School',
  'Colectivo Cafe',
  'Boone County Courthouse',
  'DePaul College Prep',
  'Quincy Station',
  'Kells (George) Park Fieldhouse',
  'Lovell VA Expand Sterile',
  'RPS Carlson',
  'The Anchorage',
  'Rosemont Elementary School',
  'East Chicago Central High School',
  'Wintrust Community Bank',
  'Argo Ingredion Project',
];

export const BRANDS = ['Tremco', 'Sika', 'W.R. Meadows', 'Henry', 'GCP', 'Xypex', '3M'];

export const WORK_TYPES = [
  'Dampproofing',
  'Waterproofing',
  'Traffic Coatings',
  'Air Barrier',
  'Firestopping',
  'Joint Sealants',
  'Flashing',
  'Primer',
];

export const UNITS = ['Units', 'Pails', 'Boxes', 'Pallets'];

export const TOOLS = [
  'Caulking Gun', 'Heat Gun', 'Mixer / Drill',
  'Notched Trowel', 'Roller', 'Sprayer', 'Grinder', 'Power Washer',
  'Rope', 'Hose',
];

export const PRODUCTS_BY_BRAND_AND_TYPE = {
  'Tremco': {
    'Waterproofing':    ['TREMproof 250GC', 'TREMproof 260', 'TREMproof PUMA', 'Paraseal GM', 'Paraseal LG'],
    'Traffic Coatings': ['Vulkem 350', 'Vulkem 351', 'Vulkem 950 NF', 'Vulkem 951 NF'],
    'Air Barrier':      ['ExoAir 230', 'ExoAir 230 Low - Temp', 'ExoAir 130', 'ExoAir 130 Low - Temp'],
    'Joint Sealants':   ['Dymonic 100', 'Spectrum 1', 'Spectrum 2', 'Spectrum 3'],
    'Flashing':         ['ExoAir 110AT 6"', 'ExoAir 110AT 9"', 'ExoAir 110AT 12"'],
  },
  'Sika': {
    'Dampproofing':     ['Sikalastic - 310', 'Sikalastic - 314', 'Sikalastic - 315'],
    'Traffic Coatings': ['Sikalastic Vehicular Traffic 2000', 'Sikalastic Vehicular Traffic 2500', 'Sikalastic Vehicular Traffic 2575', 'Sikalastic Vehicular Traffic 2850', 'Sikalastic Vehicular Traffic 2900'],
    'Joint Sealants':   ['Sikaflex - 2c SL', 'Sikaflex - 2c NS EZ Mix', 'Sikaflex -1A', 'Sikaflex -1c SL'],
  },
  'W.R. Meadows': {
    'Dampproofing':  ['SealMastic Type I', 'SealMastic Type II', 'SealMastic Type III'],
    'Waterproofing': ['Mel - Rol', 'Precon', 'Precon Low - Temp', 'MEL - DRAIN'],
    'Air Barrier':   ['Air-Shield LSR', 'Air-Shield LMP', 'Air-Shield LSR Low - Temp', 'Air-Shield LMP Low - Temp', 'Air-Shield', 'Air-Shield Low - Temp'],
    'Joint Sealants': ['BEM'],
    'Flashing':      ['AirShield 6"', 'AirShield 9"', 'AirShield 12"', 'AirShield Butyl Flashing 4"', 'AirShield Butyl Flashing 6"', 'AirShield Butyl Flashing 9"', 'AirShield Butyl Flashing 12"'],
    'Primer':        ['Mel-Prime'],
  },
  'Henry': {
    'Waterproofing': ['Blueskin VP100', 'Pumadeq'],
    'Air Barrier':   ['Air-Bloc 16MR', 'Air-Bloc 17MR', 'Barritech NP Fire - Resistant', 'Barritech NP Fire - Resistant Low - Temp', 'Barritech VP', 'Blueskin SA', 'Blueskin VP160', 'CCW - 705', 'CCW - 705 Low - Temp', 'CCW - 702'],
    'Flashing':      ['Blueskin SA Flashing 4"', 'Blueskin SA Flashing 6"', 'Blueskin SA Flashing 9"', 'Blueskin SA Flashing 12"'],
    'Primer':        ['Blueskin'],
  },
  'GCP': {
    'Waterproofing': ['Bituthene 3000', 'Bituthene 4000'],
    'Air Barrier':   ['Perm-A-Barrier'],
  },
  'Xypex': {
    'Waterproofing': ['Xypex'],
  },
  '3M': {
    'Firestopping': ['3M Fire Barrier Water Tight Spray', '3M FireDam Spray 200'],
  },
};
