export const LANG = {
  en: {
    appSub: 'Bofo Waterproofing Systems',
    formTitle: 'Request form',
    formSub: 'Submit a material, tool, or other request',
    adminTitle: 'Admin dashboard',
    adminSub: 'Manage and update all submissions',
    navForm: 'New request',
    navLog: 'Submissions',
    navAdmin: 'Admin',
    employeeName: 'Employee',
    jobSite: 'Job site',
    requestType: 'Request type',
    brand: 'Brand',
    product: 'Product',
    tool: 'Tool',
    describeItem: 'Describe item',
    quantity: 'Quantity',
    notes: 'Notes',
    notesPlaceholder: 'Additional details or instructions...',
    submit: 'Submit request',
    submitting: 'Submitting...',
    selectName: 'Select name...',
    selectSite: 'Select site...',
    selectBrand: 'Select brand...',
    selectTool: 'Select tool...',
    productPlaceholder: 'e.g. TREMproof 250GC',
    descPlaceholder: 'What do you need?',
    material: 'Material',
    toolType: 'Tool',
    other: 'Other',
    successTitle: 'Request submitted',
    successSub: 'Your request has been logged and is pending review.',
    newRequest: 'Submit another request',
    logEmpty: 'No submissions yet.',
    adminEmpty: 'No submissions yet.',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusCompleted: 'Completed',
    required: 'Please fill in all required fields.',
    errorMsg: 'Something went wrong. Please try again.',
    details: 'Details',
    qty: 'Qty',
    markApproved: 'Approve',
    markCompleted: 'Complete',
    markPending: 'Reset',
    allStatuses: 'All statuses',
    allSites: 'All sites',
    searchPlaceholder: 'Search by name or site...',
    totalSubmissions: 'Total',
    pendingCount: 'Pending',
    approvedCount: 'Approved',
    completedCount: 'Completed',
    neededBy: 'Needed by',
    neededByPlaceholder: 'e.g. ASAP, Friday, end of week...',
    priority: 'Priority',
    priorityUrgent: 'Urgent',
    priorityNormal: 'Normal',
  },
  es: {
    appSub: 'Bofo Waterproofing Systems',
    formTitle: 'Formulario de solicitud',
    formSub: 'Envía una solicitud de material, herramienta u otro',
    adminTitle: 'Panel de administración',
    adminSub: 'Gestiona y actualiza todas las solicitudes',
    navForm: 'Nueva solicitud',
    navLog: 'Envíos',
    navAdmin: 'Admin',
    employeeName: 'Empleado',
    jobSite: 'Sitio de trabajo',
    requestType: 'Tipo de solicitud',
    brand: 'Marca',
    product: 'Producto',
    tool: 'Herramienta',
    describeItem: 'Describir artículo',
    quantity: 'Cantidad',
    notes: 'Notas',
    notesPlaceholder: 'Detalles o instrucciones adicionales...',
    submit: 'Enviar solicitud',
    submitting: 'Enviando...',
    selectName: 'Selecciona nombre...',
    selectSite: 'Selecciona sitio...',
    selectBrand: 'Selecciona marca...',
    selectTool: 'Selecciona herramienta...',
    productPlaceholder: 'ej. TREMproof 250GC',
    descPlaceholder: '¿Qué necesitas?',
    material: 'Material',
    toolType: 'Herramienta',
    other: 'Otro',
    successTitle: 'Solicitud enviada',
    successSub: 'Tu solicitud ha sido registrada y está pendiente de revisión.',
    newRequest: 'Enviar otra solicitud',
    logEmpty: 'Sin envíos aún.',
    adminEmpty: 'Sin envíos aún.',
    statusPending: 'Pendiente',
    statusApproved: 'Aprobado',
    statusCompleted: 'Completado',
    required: 'Por favor completa todos los campos requeridos.',
    errorMsg: 'Algo salió mal. Por favor intenta de nuevo.',
    details: 'Detalles',
    qty: 'Cantidad',
    markApproved: 'Aprobar',
    markCompleted: 'Completar',
    markPending: 'Restablecer',
    allStatuses: 'Todos los estados',
    allSites: 'Todos los sitios',
    searchPlaceholder: 'Buscar por nombre o sitio...',
    totalSubmissions: 'Total',
    pendingCount: 'Pendientes',
    approvedCount: 'Aprobados',
    completedCount: 'Completados',
    tools: ['Pistola de sellado', 'Pistola de calor', 'Mezclador / Taladro', 'Llana dentada', 'Rodillo', 'Rociador', 'Amoladora', 'Hidrolavadora'],
    neededBy: 'Necesito para',
    neededByPlaceholder: 'ej. Lo antes posible, viernes, fin de semana...',
    priority: 'Prioridad',
    priorityUrgent: 'Urgente',
    priorityNormal: 'Normal',
  }
};

export const EMPLOYEES = [
  'Carlos Mendez', 'Diego Ramos', 'Luis Torres',
  'Miguel Reyes', 'Roberto Castillo', 'Andres Navarro',
];

export const JOB_SITES = [
  'Site A – Oak Lawn', 'Site B – Cicero',
  'Site C – Bridgeview', 'Site D – Evergreen Park', 'Site E – Burbank',
];

export const BRANDS = ['Tremco', 'Sika', 'BASF', 'W.R. Grace', 'Henry', 'GCP Applied'];

export const TOOLS = [
  'Caulking Gun', 'Heat Gun', 'Mixer / Drill',
  'Notched Trowel', 'Roller', 'Sprayer', 'Grinder', 'Power Washer',
];
